#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III
bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# AUTOSTART
$HOME/.config/polybar/launch.sh
feh --randomize --bg-center $HOME/Wallpapers/*
# bspc rule -a -o firefox desktop=1
bspc rule -a firefox desktop='^1'
